name: Continuous yyyyy
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '10 * * * *'
    - cron:  '20 * * * *'
    - cron:  '30 * * * *'
    - cron:  '40 * * * *'
    - cron:  '50 * * * *'

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: yy
        run : echo "yy"
