name: Continuous yyyyy
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '10 * * * *'
    - cron:  '20 * * * *'
    - cron:  '30 * * * *'
    - cron:  '40 * * * *'
    - cron:  '50 * * * *'
    - cron:  '5 * * * *'
    - cron:  '15 * * * *'
    - cron:  '25 * * * *'
    - cron:  '35 * * * *'
    - cron:  '45 * * * *'
    - cron:  '55 * * * *'

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: us-west-2
      - name: yy
        run : aws cloudwatch put-metric-data --metric-name XRayJavaSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 1 --timestamp $(date +%s)
