name: Continuous yyyyy
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'
    - cron:  '10 */1 * * *'
    - cron:  '20 */1 * * *'
    - cron:  '30 */1 * * *'
    - cron:  '40 */1 * * *'
    - cron:  '50 */1 * * *'

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: yy
        run : echo "yy"
